gemini-hlsw/sbt-lucuma

project/plugins.sbt
[I found this idea](https://engineering.sharethrough.com/blog/2015/09/23/capturing-common-config-with-an-sbt-parent-plugin/) to use the shared settings for the plugin itself.  So, for example, an unused import in the plugin implementation will stop the build.
=> Use the shared settings

build.sbt, src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This moves the header settings to the shared build settings plugin so they don't have to be specified in each project.
=> Share header settings

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This is at least an initial attempt at #3.  It includes the settings used by `gsp-math` and may be referenced in a build via:
```scala
.jsSettings(gspScalaJsSettings: _*)
```
instead of explicitly listing them each time
```scala
.jsSettings(
scalacOptions ~= (_.filterNot(Set("-Xcheckinit"))),
scalacOptions += "-P:scalajs:sjsDefinedByDefault"
)
```
=> Shared JS Settings

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This adds the sonatype public resolver, which will let our projects see our own published artifacts more quickly (they get pushed to Maven Central eventually but it can take a few hours).
(Ironically this won't let us see sbt-gsp releases more quickly, which makes sense if you think about it.)
=> add sonatype public resolver

.travis.yml, build.sbt, project/plugins.sbt, src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This sets up GSP projects to cross-build for 2.12 and 2.13, at least until the SeqExec is on 2.13 at which point we can remove 2.12.
Because the compiler flags are different between 2.12 and 2.13 I removed the long list and added the `sbt-tpolecat` plugin (which I did not write) which enforces the same set of options with variations to accommodate different compiler versions.
=> Cross-build for 2.13

build.sbt
Need to disable the plugin we're building otherwise the plugin will try to cross-publish. This was making the auto-publish fail.
=> disable self-referenced plugin

.jvmopts, src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
+ Move gspGlobalSettings to globalSettings. Rather than having global defaults propagated directly to projects we define them as globals allowing them to be inherited by the build and projects, or overridden at the build level.
+ Added .jvmopts to enable colour and super shell on zsh when building sbt-gsp itself.
=> Update for SBT 1.3.0 and Scala 2.13.0

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
downstream projects will need to run `headerCreate` to update copyright headers
=> update header, add raúl

.gitignore, build.sbt, project/plugins.sbt, src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This PR allows us to use `scalafix OrganizeImports` on the projects. I suppose we can add more rules in the future. Note that it doesn't force you to use it but it makes it very easy to do so
Based on https://github.com/gemini-hlsw/gpp-ui/pull/5
=> Include OrganizeImports and scalafix

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This works around a bug between the versions of scalafix and scalameta which makes it fail if you use scala 2.13.2
=> Add explicit semanticdb version

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
That compiler option causes troubles while working on scala.js 1.0
=> Remove compiler option for scala.js 0.6

.gitignore, build.sbt, project/plugins.sbt, src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This PR makes warnings non-fatal in development environments while keeping them fatal in CI environments.
`rewarn` is used so that all unresolved warnings are always reported in every compilation  whereas the current compilation units produce the warnings or not).
=> Non-fatal warnings in dev + rewarn.

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
Apparently you don't need it anymore in newer scala versions, or so they say
https://docs.scala-lang.org/scala3/guides/migration/tutorial-prerequisites.html#semanticdb
=> Remove explicit semanticdb plugin

build.sbt, src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala
This adds two things to the default build configuration, with the goal of making it safer for us to evolve our libraries independently and make it clear when downstream updates are and are not compatible.
- Artifacts we publish will now include metadata about the version scheme we're using, which will help SBT detect cases where evictions are not legal. For example, if you end up depending on lucuma-woozle versions 1.2.3 and 1.2.4, it will just use 1.2.4; but if you're depending o 1.2.3 and 4.5.6, sbt will fail the build because the version scheme says these versions are incompatible. The scheme I chose is early-semver (described [here](https://www.scala-sbt.org/1.x/docs/Publishing.html#Version+scheme)) which is what most Scala libraries use.
- Builds will now include …
=> add mima, version scheme

.github/workflows/ci.yml, app/src/main/scala/lucuma/sbtplugin/LucumaAppPlugin.scala, build.sbt, core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala, lib/src/main/scala/lucuma/sbtplugin/LucumaLibPlugin.scala, project/plugins.sbt
So, this is a bit embarrassing :)
For some reason I couldn't track down the latest snapshot. Well, turns out it was published under `org.typelevel` 😅
After the plugin re-organizing in https://github.com/gemini-hlsw/sbt-lucuma/pull/145, the sbt-lucuma core plugin (which sets your publish settings) and the sbt-typelevel plugin (which sets Typelevel publish settings) now ended up at the "same level". Previously, sbt-lucuma depended on sbt-typelevel so the sbt-lucuma publish settings took priority. However, post-https://github.com/gemini-hlsw/sbt-lucuma/pull/145 sbt-lucuma-lib depends on both sbt-lucuma and sbt-typelevel (hence they are at the "same level"). The plugins were loaded in an arbitrary order and sbt-typelevel publish settings overrode the sbt-lucuma publish settings.
To mitigate …
=> Fix publish settings

.github/workflows/ci.yml, core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
So I bungled this a bit 😅 Enabling coverage in CI not only enables it for tests, but also enables it for the publish step which messes up the published artifacts. These changes make sure that coverage is enabled only for the build/test job, and that the publish step recompiles the code without coverage enabled.
=> Only enable coverage in build job

build.sbt
Propagating a bug fix from https://github.com/typelevel/sbt-typelevel/pull/139. I'll make sure to get this on something stable before  release.
=> Update to sbt-typelevel 0.4.3-32-5fff779

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
In practice this shouldn't make really make a difference. Currently we're losing these steps in the app plugin due to:
https://github.com/gemini-hlsw/sbt-lucuma/blob/16bd6e7f7d2a296f4b52a560aa5d9fc366673057/app/src/main/scala/lucuma/sbtplugin/LucumaAppPlugin.scala#L49-L50
The underlying problem is that manipulating these workflow steps programmatically is still much too brittle. I've been exploring some solutions to this problem in https://github.com/typelevel/sbt-typelevel/pull/102.
=> Move coverageReport step to postamble

build.sbt, core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
Apparently the default names for the dependency resolvers were conflicting with the names for the publishing resolvers 😕
=> Manually add resolvers

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
In CI they become fatal errors, like your compiler warnings. This makes it possible to test snapshots etc. locally.
=> Only warn about eviction errors in local development

.mergify.yml, build.sbt, css/src/main/scala/lucuma/sbtplugin/LucumaCssPlugin.scala, css/src/sbt-test/lucuma-css/example/build.sbt, css/src/sbt-test/lucuma-css/example/project/build.properties, css/src/sbt-test/lucuma-css/example/project/plugins.sbt, css/src/sbt-test/lucuma-css/example/test
This plugin gathers all CSS-like resource files in a project and its dependencies and copies them to the `target/lucuma-css` directory on `fastLinkJS` / `fullLinkJS`.
It has to be explicitly enabled with `.enablePlugins(LucumaCssPlugin)`. It is only needed by applications that want to use the CSS.
Library projects that just want to publish CSS need only to plop it in the `resources/lucuma-css` directory and be on their merry way; they do not require this plugin.
=> sbt-lucuma-css

core/src/main/scala/lucuma/sbtplugin/LucumaScalaJSPlugin.scala
Any binary-incompatibilities will be caught at linking-time anyway.
=> Make eviction errors non-fatal on JS

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
This allows to use APIs included in up to JDK 17, as well as emits optimized bytecode.
=> Set `tlJdkRelease := Some(17)`

.github/workflows/ci.yml, core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
1. Add a new setting to enable/disable coverage. When `false` it will remove all coverage related steps from the workflow
```scala
ThisBuild / lucumaCoverage := false
```
2. Tweak the detection logic used to enable coverage for a sub project. If it's working correctly, it should be enabled for any JVM while running during the test step in CI.
3. Use the codecov github action instead of the bash script download, hopefully this should be more reliable.
=> Try to fix coverage

.github/workflows/ci.yml, core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
This way we properly respect the setting of `tlCiScalafmtCheck` etc.
=> Re-use existing header/scalafmt check step

build.sbt, core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
CI for `lucuma-odb` complains that it cannot find `docker-compose`.  Presumably it is now `docker compose` instead?  This is an attempt to fix it.  Since I have no idea how any of this works, somebody who knows better should review this.
=> docker compose

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
With scala 3.7 there are more instances where we need to use `@nowarn`. This will let us know if we are unnecessarily suppressing warning.
=> Add `-Wunused:nowarn`

.gitignore, .mergify.yml, build.sbt, docker/src/main/resources/lucuma/sbtplugin/heroku-docker-set-memory.sh, docker/src/main/scala/lucuma/sbtplugin/LucumaDockerPlugin.scala, project/plugins.sbt
Create a new `sbt-lucuma-docker` plugin that configures the native packager with our usual Docker settings, plus adding our manual mechanism for dynamic memory allocation that seems to be needed when deploying images to Heroku.
=> Docker deploy plugin
