build.sbt
src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Incorporates shared publish settings.

Add publish settings

---

build.sbt
src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

The publish plugin was apparently not happy with the first attempt.  Trying again.  Unfortunately I don't know how to try this one without attempting an actual publish via a PR.

Publish settings take 2

---

build.sbt
src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Publishing is not working, so I'm trying to back out of my attempt for now.

Undo sharing publish settings

---

build.sbt
src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Another attempt to share publish settings.

Take 3, sharing publish settings

---

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

add global settings with scala version

---

project/plugins.sbt

With this change publishing should be much faster and more reliable for downstream projects. Fingers crossed.

update sbt-ci-release to 1.3.1

---

.mergify.yml

Setup mergify

---

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Signed-off-by: Carlos Quiroz <carlos.m.quiroz@gmail.com>

Upgrade to scala 2.13.2

---

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Updates organize imports

---

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

We can upgrade now that metals supports 2.13.3

Scala update

---

.github/workflows/scala.yml
build.sbt
src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Let's make the plug-in names consistent with the other projects

Add Todd and rename gsp to lucuma

---

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Upgrade libs

---

.github/dependabot.yml
.github/workflows/release.yml
.github/workflows/scala.yml

Fixes the build

---

.gitignore
src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Scalameta needs a specific version for scala 2.13.4

Update scalameta/organize imports

---

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Signed-off-by: Carlos Quiroz <carlos.m.quiroz@gmail.com>

Update semantic db

---

src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Update organize imports

---

project/plugins.sbt
src/main/scala/edu/gemini/gsp/sbtplugin/GspPlugin.scala

Signed-off-by: Carlos Quiroz <carlos.quiroz@noirlab.edu>

Update copyright year

---

app/src/main/scala/lucuma/sbtplugin/LucumaAppPlugin.scala

Remove unnecessary steps from app CI

---

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

If a `docker-compose.yml` is detected in the repo the necessary up/down steps are automatically added to CI.

Automatically support docker-compose

---

.github/workflows/ci.yml
app/src/main/scala/lucuma/sbtplugin/LucumaAppPlugin.scala
core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

This only affects the app plugin.

Default CI to JDK 17 only

---

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

Disable scoverage on Scala 3

---

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

Use `LocalRootProject` to detect Scala 3

---

.github/workflows/ci.yml
.scalafmt-common.conf
build.sbt
core/src/main/resources/lucuma/sbtplugin/scalafmt-common.conf
project/plugins.sbt

This gets us on a stable release.

Update sbt-typelevel and scalafmt

---

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

Companion PR to:
- https://github.com/scala-steward-org/scala-steward/pull/2521
Steward will run this command whenever there is a sbt-lucuma update. This makes it easy to automatically propagate changes to headers, formatting, etc.

Create `tlPrePrBotHook` command alias

---

build.sbt
sjs-bundler/src/main/scala/lucuma/sbtplugin/LucumaSJSBundlerPlugin.scala
sjs-bundler/src/sbt-test/lucuma-sjs-bundler/example/build.sbt
sjs-bundler/src/sbt-test/lucuma-sjs-bundler/example/modules/foo/package.json
sjs-bundler/src/sbt-test/lucuma-sjs-bundler/example/package.json
sjs-bundler/src/sbt-test/lucuma-sjs-bundler/example/project/build.properties
sjs-bundler/src/sbt-test/lucuma-sjs-bundler/example/project/plugins.sbt
sjs-bundler/src/sbt-test/lucuma-sjs-bundler/example/test

Riffing on my idea with @toddburnside to load Scala.js bundler npm dependencies from `package.json` files which are updated by dependabot. Still need to test this :)

Introduce `LucumaSJSBundlerPlugin`

---

sjs-bundler/src/main/scala/lucuma/sbtplugin/LucumaSJSBundlerPlugin.scala

Thanks to feedback from @rpiaggio!

Improvements for SJSBundlerPlugin

---

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

That's what it says :)
https://github.com/scalacenter/sbt-scalafix/blob/7697ec9f958ae3888720832e882d4f0c90a02386/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L60-L64

Scalafix deps are build-level

---

.mergify.yml
core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

Fix mergify steward config

---

.github/workflows/ci.yml
app/src/main/scala/lucuma/sbtplugin/LucumaAppPlugin.scala
core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

If nobody is reading them, at least we can shave a minute or two from CI.

Generate empty scaladocs

---

css/src/main/scala/lucuma/sbtplugin/LucumaCssPlugin.scala

sbt caching docs were pretty overwhelming, so this was a shot in the dark, let's give it a try 🤞 
https://www.scala-sbt.org/1.x/docs/Caching.html

Support caching for lucuma-css

---

.mergify.yml
build.sbt
jsdom/src/main/scala/lucuma/LucumaJSDOMNodeJSEnv.scala

Via:
- https://github.com/gemini-hlsw/lucuma-react/pull/398

Upstream hacked JSDOM env

---

core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala

Workaround for:
- https://github.com/fthomas/refined/pull/1317

Silence warnings for `WitnessAs`

---

app/src/main/scala/lucuma/sbtplugin/LucumaAppPlugin.scala
core/src/main/scala/lucuma/sbtplugin/LucumaBundleMonPlugin.scala
core/src/main/scala/lucuma/sbtplugin/LucumaPlugin.scala
core/src/main/scala/lucuma/sbtplugin/LucumaScalaJSPlugin.scala
core/src/main/scala/lucuma/sbtplugin/LucumaScalafixPlugin.scala
core/src/main/scala/lucuma/sbtplugin/LucumaScalafmtPlugin.scala
css/src/main/scala/lucuma/sbtplugin/LucumaCssPlugin.scala
jsdom/src/main/scala/lucuma/LucumaJSDOMNodeJSEnv.scala
lib/src/main/scala/lucuma/sbtplugin/LucumaLibPlugin.scala
sjs-bundler/src/main/scala/lucuma/sbtplugin/LucumaSJSBundlerPlugin.scala

We seem to have missed this last year :D

Update (c) year

---

core/src/main/scala/lucuma/sbtplugin/LucumaBundleMonPlugin.scala

that's not the correct way to skip errors with bundlemon

This is not working
